name: "CodeQL"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # schedule:
  #   - cron: '0 0 * * 0'

permissions:
  security-events: write

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    # - name: Autobuild
    #   uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Gate
      if: ${{ always() }}
      uses: ./actions/sec/gate
      id: hello
      with:
          # github_token: ${{ secrets.token }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_owner: gitsebste
          repo_name: public
          target_ref: refs/heads/main
